# Generated by Django 4.2.1 on 2023-06-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Circuit",
            fields=[
                (
                    "circuitId",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("circuitRef", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=300, unique=True)),
                ("location", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=1000)),
                ("layoutUrl", models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Constructor",
            fields=[
                (
                    "constructorId",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("constructorRef", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("nationality", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=1000)),
                ("logoUrl", models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "driverId",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("driverRef", models.CharField(max_length=100, unique=True)),
                ("number", models.IntegerField(null=True)),
                ("code", models.CharField(max_length=3, null=True)),
                ("forename", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("nationality", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("photoUrl", models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Grid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "constructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="f1dataapp.constructor",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="f1dataapp.driver",
                    ),
                ),
            ],
        ),
    ]
