# Generated by Django 4.2.1 on 2023-06-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f1dataapp", "0002_remove_driver_photourl_driver_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circuit",
            name="layoutUrl",
        ),
        migrations.RemoveField(
            model_name="constructor",
            name="logoUrl",
        ),
        migrations.AddField(
            model_name="circuit",
            name="layout",
            field=models.ImageField(null=True, upload_to="circuit_layouts"),
        ),
        migrations.AddField(
            model_name="constructor",
            name="logo",
            field=models.ImageField(null=True, upload_to="team_logos"),
        ),
    ]
