# Generated by Django 4.2.1 on 2023-06-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "f1dataapp",
            "0003_remove_circuit_layouturl_remove_constructor_logourl_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="circuit",
            name="is_recent",
            field=models.BooleanField(default=False),
        ),
    ]
